FROM python:3.12 AS base

# Переменные окружения для Python и pip
ARG PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=on \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=500

RUN apt-get update && apt-get install -y gcc

RUN python -m pip install --upgrade pip

WORKDIR /hse-python-backend-1

COPY . .  

# Установка виртуального окружения и добавление в PATH
ENV VIRTUAL_ENV=/hse-python-backend-1/.venv \
    PATH="/hse-python-backend-1/.venv/bin:$PATH"

# Установка зависимостей из requirements.txt
RUN pip install -r lecture_2/hw/shop_api/requirements.txt

# Раздел для разработки (dev)
FROM base as dev

# Команда для удержания контейнера в активном состоянии
CMD ["bash", "-c", "while true; do sleep 1; done"]

# Локальный раздел для запуска приложения (local)
FROM base as local

# Запуск приложения через Uvicorn
CMD ["uvicorn", "lecture_2.hw.shop_api.main:app", "--port", "8080", "--host", "0.0.0.0"]

