services:
  app:
    build:
      context: .. 
      dockerfile: lecture_2/hw/shop_api/docker/Dockerfile  # Путь к Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./hw/shop_api/settings/prometheus.yaml:/etc/prometheus/prometheus.yml  # Указан полный путь к prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus









